apiVersion: v1
kind: Service
metadata:
  name: orderserviceservice
spec:
  type: NodePort
  selector:
    app: orderservice
  ports:
    - protocol: TCP
      nodePort: 30081
      port: 9743
      targetPort: 9743